In [1]:
import numpy as np

In [2]:
# a list of 2
Z = 2*np.ones(9)
print(Z)

[2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [3]:
# a range
Z = np.arange(9)
print(Z)

[0 1 2 3 4 5 6 7 8]


In [8]:
# reshape
Z = np.arange(9).reshape(9,1)
print(Z)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [10]:
# random matrix, numbers
Z=np.random.randint(0,9,(3,3))
print(Z)

[[1 6 2]
 [2 3 7]
 [1 8 7]]


In [11]:
# linspace, like bins
#  np.linspace(start, stop, size)
Z = np.linspace(0, 1, 5)
print(Z)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
Z=np.mgrid[0:3,9:14]
print(Z)

[[[ 0  0  0  0  0]
  [ 1  1  1  1  1]
  [ 2  2  2  2  2]]

 [[ 9 10 11 12 13]
  [ 9 10 11 12 13]
  [ 9 10 11 12 13]]]


In [16]:
# one demension reshape to multidimension
Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(3,4)
print(Z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]


In [17]:
# how to use ':'
Z = np.arange(9).reshape(3,3)
print(Z[1:,1:])

[[4 5]
 [7 8]]


In [18]:
# corner of a grid
Z = np.arange(9).reshape(3,3)
print(Z[::2,::2])

[[0 2]
 [6 8]]
